<?php
// check_attendance.php
header('Content-Type: application/json');

$servername = "localhost";
$username = "root";
$password = "";
$dbname = "rfid_system";

$uid = $_GET['uid']; // Get UID from URL

// Create connection
$conn = mysqli_connect($servername, $username, $password, $dbname);

if (!$conn) {
    echo json_encode(["error" => "Database connection failed"]);
    exit();
}

// Get the user's entry and exit time from registered_user table
$sql = "SELECT entry_time, exit_time FROM registered_user WHERE uid = '$uid'";
$result = mysqli_query($conn, $sql);

if (mysqli_num_rows($result) > 0) {
    $row = mysqli_fetch_assoc($result);
    
    $entry_time = $row['entry_time'];
    $exit_time = $row['exit_time'];
    
    // Get current time in HH:MM:SS format
    $current_time = date('H:i:s');
    
    // Check if current time is within the entry and exit time
    if ($current_time >= $entry_time && $current_time <= $exit_time) {
        
        // Insert attendance record into attendance_record table
        // The timestamp will be automatically generated by the database
        $attendance_sql = "INSERT INTO attendance_record (uid) VALUES ('$uid')";
        
        if (mysqli_query($conn, $attendance_sql)) {
            echo json_encode(["success" => "Attendance recorded successfully"]);
        } else {
            echo json_encode(["error" => "Failed to record attendance"]);
        }
        
    } else {
        echo json_encode(["error" => "Attendance not allowed outside the specified time range"]);
    }
} else {
    echo json_encode(["error" => "User not found"]);
}

mysqli_close($conn);
?>
